### PR TITLE
optimizations and improvements

### PR DESCRIPTION
**Pull request by mandar1jn**
I did a lot of optimizations and improvements. Check the commits for more information

### CODE REVIEW

**Review by AffluentAvo — APPROVED** [review]

**Review by AffluentAvo — CHANGES_REQUESTED** [review]
The changes in ServerCommand.java changed unicode characters to a question mark-sign.
In Database.java, we added the possibility to use SQLite, so if other people who want to run the bot, don't have to use a mysql-database.

**Comment by mandar1jn** [comment]
@AffluentAvo all the unicode characters should be fixed now

**Review by AffluentAvo — APPROVED** [review]

**Comment by AffluentAvo** [comment]
Waiting for @PolyMarsDev to merge, because he might have made local changes to the code and wants to update that first.

**Comment by mandar1jn** [comment]
@AffluentAvo great!

**Pull request closed without merging**
